apiVersion: apps/v1
kind: Deployment
metadata:
  name: fo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fo
  template:
    metadata:
      labels:
        app: fo
    spec:
      containers:
        - name: fo
          image: rasztabigab/fo:0.0.6
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fo-service
spec:
  selector:
    app: fo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fo-ingress
spec:
  rules:
    - host: fo.rasztabiga.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fo-service
                port:
                  number: 3000
